version: '2.2'
services:
    php: 
        build: ./services/php
        ports: 
            - "9000:9000"
        container_name: lnmp-php
        restart: always
        volumes: 
            - ./sites:/var/www/html:rw
        links:
            - mysql
    nginx:
        image: nginx:alpine
        ports: 
            - "80:80"
            - "443:443"
        container_name: lnmp-nginx
        restart: always
        depends_on: 
            - php
        volumes: 
            - ./sites:/usr/share/nginx/html
            - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    redis: 
        image: redis:latest
        ports: 
            - "6379:6379"
        container_name: lnmp-redis
        restart: always
    mysql:
        image: mysql:5.7
        ports: 
            - "3305:3306"
        container_name: lnmp-mysql
        restart: always
        environment:
            MYSQL_USER: leslie
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
networks:
    lnmp_net:
        driver: bridge
        ipam:
            config:
                - subnet: 127.0.0.1/20

        